### ISSUE TITLE
Wind vector nord reference

### ISSUE THREAD

**Issue by rbonvino** [neoground/neowx#12]
Not an issue, just a request. Could you put the reference to the north direction in the wind vector graph? Thankyou very much.

**Comment by neoground** [comment]
The reference is already on the graphs, just very tiny. I increased the size.

Recently I also created a new skin which includes many improvements and new features. Instead of a wind vector graph, which might look confusing some times, it generated interactive graphs and a wind rose with all directions and their respective wind speeds. You can find more information here: https://neoground.com/projects/neowx-material
