### ISSUE TITLE
Incorrect Roboto fonts path on Raspbian GN/Linux 10 (Buster)

### ISSUE THREAD

**Issue by Attilio57** [neoground/neowx#20]
Today I installed NeoWx package and Roboto fonts to test them. I'm using Raspbian 10 (Buster) and Weewx latest version to manage and publish my Davis VantageVue weather station data.

In skin.cnf Roboto .tff files path is /usr/share/fonts/truetype/roboto/hinted/. 

But after I installed the fonts package with "sudo apt install fonts roboto" (as suggested in GitHub instructions), I found them in an another path, /usr/...unhinted/. 

It isn't a great issue, I modified the skin.conf file and now all is OK. Could it be a difference because I'm using Raspbian?

**Comment by scottjl** [comment]
Same issue here with Ubuntu 20.04, the package is no longer hinted and now resides at /usr/share/fonts/truetype/roboto/unhinted/

**Comment by Attilio57** [comment]
So it could be the current default path for these fonts. Un update of skin.conf file and GitHub package Install Fonts instructions could easily fix the issue.

**Comment by neoground** [comment]
Due to different platforms paths will always be different, especially on non-linux systems. But it seems that the path will be unhinted on most linux systems, so I will update the skin.conf.

Recently I released a new skin, NeoWX Material, which contains interactive graphs and doesn't generate images, so these problems are finally gone. It was always a bit troublesome to get graphs working on weewx on different machines. If you're interested you can find out more here: https://neoground.com/projects/neowx-material
