### ISSUE TITLE
Majority of current graphs blank

### ISSUE THREAD

**Issue by thron2002** [neoground/neowx#7]
Firstly, thank you for the great looking skin. 

I am running into a strange issue that I have not been able to solve. It seems almost all the graphs in the current view are blank. The only graph that isn't blank is the wind vector graph. All other graphs in the Week, Month and Year pages generate fine. I've gone through the configuration several times and it appears to be correct. 

Could you offer any pointers as to what might be the issue?

**Comment by neoground** [comment]
Does the wind vector graph show valid data?
It seems that there are some issues passing the data to the graph generator.  You could check this section of your config. You can find more information on this in the official weewx docs. Does weewx archive the correct values in the database?

I guess the easiest way would be to reinstall weewx with a clean config. You can import your archive later again, just backup your weewx.conf and do every config change step by step again.

**Comment by Maginos2210** [comment]
I think I know the solution for this problem, because I had this issue as well and for the solution I'd like to cite a part of the "Troubleshooting" section of the weewx Users guide ([http://www.weewx.com/docs/usersguide.htm#dots_in_plots]):

If you see dots instead of lines in the daily plots, you might want to change the graphing options or adjust the station's archive interval.

In a default configuration, a time period greater than 1% of the displayed timespan is considered to be a gap in data. So when the interval between data points is greater than about 10 minutes, the daily plots show dots instead of connected points.

Change the line_gap_fraction option in skin.conf to control how much time is considered a break in data.

As for the archive interval, check the log file for an entry like this soon after WeeWX starts up:

Dec 30 10:54:17 saga weewx[10035]: wxengine: The archive interval in the configuration file (300) does not match the station hardware interval (1800).
Dec 30 10:54:17 saga weewx[10035]: wxengine: Using archive interval of 1800

In this example, interval in weewx.conf is 5 minutes, but the station interval is 30 minutes. When the interval in weewx.conf does not match the station's hardware interval, WeeWX defers to the station's interval.

Use the wee_device utility to change the station's interval.


I set the line_gap_fraction = 0.02 in my skin.conf and now it's working fine with a station hardware interval (= archive_inverval in weewx.conf) of 1800 and I also changed the polling method. In the weewx.conf file, I commented out the option polling_interval = xyz and inserted the line polling_mode = ADAPTIVE
This asks the station every 48 seconds for new data, so if the station has new data, 48 s at maximum later, the newest data will be pulled from the station and uploaded to the webserver.
