### ISSUE TITLE
npm install fails on macOS with npm 10

### ISSUE THREAD

**Issue by maxxer** [neoground/neowx#8]
Full log: [2019-11-04T13_12_41_977Z-debug.log](https://github.com/neoground/neowx/files/3804663/2019-11-04T13_12_41_977Z-debug.log)

**Comment by maxxer** [comment]
Fixed with this patch, but then gulp will crash :(

```
index b498a94..5a635a0 100644
--- a/package.json
+++ b/package.json
@@ -22,6 +22,7 @@
     "gulp-load-plugins": "*",
     "gulp-sass": "*",
     "gulp-uglify": "*",
-    "gulp-rename": "*"
+    "gulp-rename": "*",
+    "nan": "^2.10.0"
   }
 }
```

**Comment by magimat** [comment]
any update?

**Comment by neoground** [comment]
Gulp has changed many things in the last few years and my build code is using a quite old version.

To make this fully working again the build system (gulp file) would need to be fully rewritten and some libs might need to be replaced.

But due to the decreasing popularity of this skin and newer available skins this doesn't make too much sense and I currently don't know when I could implement this.


Recently I released a new skin based on this, calles NeoWX Material. It includes many improvements, new features and an easy build system which will work without any problems just with npm / yarn. You can find more information here: https://neoground.com/projects/neowx-material
